### ISSUE TITLE
Won't build for distribution OR device

### ISSUE THREAD

**Issue by jasonkneen** [mbender74/ti.bottomsheetcontroller-ios#3]
Using Xcode 13, Node 12.x, Ti 10.1.0.GA I get this:

`TRACE]  ld: warning: directory not found for option '-L/Users/jkneen/Documents/Appcelerator_Studio_Workspace/walksafedev/build/iphone/lib'
[TRACE]  Undefined symbols for architecture arm64:
[TRACE]    "_OBJC_CLASS_$_TiUIListView", referenced from:
[TRACE]        objc-class-ref in libti.bottomsheetcontroller.a(TiBottomsheetcontrollerProxy.o)
[TRACE]  ld: symbol(s) not found for architecture arm64
[TRACE]  clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Works fine if I remove the module

**Comment by mbender74** [comment]
should work now!
