### ISSUE TITLE
Build failed for simulator and device

### ISSUE THREAD

**Issue by bincTW** [mbender74/ti.bottomsheetcontroller-ios#5]
Module Version 1.1.0 (also tried 1.0.9, 1.0.6)
Xcode 12.4 
Titanium SDK 10.1.1.GA
Node 14.19.3

`TRACE]  Undefined symbols for architecture x86_64:
[TRACE]    "_UISheetPresentationControllerDetentIdentifierMedium", referenced from:
[TRACE]        -[TiBottomsheetcontrollerProxy selectedDetentIdentifier] in libti.bottomsheetcontroller.a(TiBottomsheetcontrollerProxy.o)
[TRACE]        -[TiBottomsheetcontrollerProxy changeCurrentDetent:] in libti.bottomsheetcontroller.a(TiBottomsheetcontrollerProxy.o)
[TRACE]        -[TiBottomsheetcontrollerProxy setLargestUndimmedDetentIdentifier:] in libti.bottomsheetcontroller.a(TiBottomsheetcontrollerProxy.o)
[TRACE]        -[TiBottomsheetcontrollerProxy updatePopoverNow] in libti.bottomsheetcontroller.a(TiBottomsheetcontrollerProxy.o)
[TRACE]        -[TiBottomsheetcontrollerProxy sheetPresentationControllerDidChangeSelectedDetentIdentifier:] in libti.bottomsheetcontroller.a(TiBottomsheetcontrollerProxy.o)
[TRACE]    "_OBJC_CLASS_$_UISheetPresentationControllerDetent", referenced from:
[TRACE]        objc-class-ref in libti.bottomsheetcontroller.a(TiBottomsheetcontrollerProxy.o)
[TRACE]    "_UISheetPresentationControllerDetentIdentifierLarge", referenced from:
[TRACE]        -[TiBottomsheetcontrollerProxy selectedDetentIdentifier] in libti.bottomsheetcontroller.a(TiBottomsheetcontrollerProxy.o)
[TRACE]        -[TiBottomsheetcontrollerProxy changeCurrentDetent:] in libti.bottomsheetcontroller.a(TiBottomsheetcontrollerProxy.o)
[TRACE]        -[TiBottomsheetcontrollerProxy setLargestUndimmedDetentIdentifier:] in libti.bottomsheetcontroller.a(TiBottomsheetcontrollerProxy.o)
[TRACE]        -[TiBottomsheetcontrollerProxy updatePopoverNow] in libti.bottomsheetcontroller.a(TiBottomsheetcontrollerProxy.o)
[TRACE]        -[TiBottomsheetcontrollerProxy sheetPresentationControllerDidChangeSelectedDetentIdentifier:] in libti.bottomsheetcontroller.a(TiBottomsheetcontrollerProxy.o)
[TRACE]  ld: symbol(s) not found for architecture x86_64
[TRACE]  clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR]  ** BUILD FAILED **`

**Comment by mbender74** [comment]
Please try 1.2.0
min iOS is 12, min TiSDK 10.1.0.GA
The systemSheetController works only from iOS 15, it defaults to nonSystemSheet if that condition does not fit....
