### ISSUE TITLE
Support iOS 16 APIs

### ISSUE THREAD

**Issue by hansemannn** [mbender74/ti.bottomsheetcontroller-ios#6]
There is a cool new API to support a detent with a flexible height (yey!). The docs are here: https://developer.apple.com/documentation/uikit/uisheetpresentationcontrollerdetent/3975903-customdetentwithidentifier?changes=latest_minor&language=objc

**Comment by mbender74** [comment]
Ok, I will put that in ;-)

**Comment by mbender74** [comment]
done!
